### ISSUE TITLE
Issue with requiring via webpack

### ISSUE THREAD

**Issue by growlsworth** [glittershark/reactable#167]
Error: Cannot find module './stringable

in [node_modules/reactable/build/reactable.js:95](https://github.com/glittershark/reactable/blob/master/build/reactable.js#L95).

I'm running on https://github.com/glittershark/reactable/releases/tag/0.11.0-beta2.

**Comment by growlsworth** [comment]
When updating to 0.11.0 I just experienced this as well.

**Comment by glittershark** [comment]
This seems to me like an issue with the naïve concatenation of modules we're doing in order to get a single UMD file. That build workflow needs to be reworked somehow... Any thoughts?

**Comment by growlsworth** [comment]
Yo, I recommend not having [`main` in package.json](https://github.com/glittershark/reactable/blob/master/package.json#L5) point to a single UMD file. If you take a look at https://github.com/fmoo/react-typeahead as a random example, the author compiles the jsx files to es5 files and puts that in lib, with the same file/folder structure. Then [`main` in package.json](https://github.com/fmoo/react-typeahead/blob/master/package.json#L41) points to that compiled version.  This allows app authors to not require babel or coffeescript or jsx or whatever in their own package (I personally appreciate that) when including the external library. Every bundling tool supports the require syntax and can figure it's own way of bundling the files. The author does have a dist folder that contains unified UMD files which could be dropped into a page.

**Comment by glittershark** [comment]
ah! alright, that's a simple enough solution.

**Comment by bastiao** [comment]
Please, fix it ASAP.

**Comment by glittershark** [comment]
If you need it fixed on a certain schedule you're welcome to submit a PR yourself

**Comment by Duan112358** [comment]
If install it via bower, and added bower_components into webpack's resolveDirectories, may be helpful

**Comment by davidblurton** [comment]
I am using the following workaround: 

  1. Copy the built version into a file called `reactable.js`
  2. npm install `expose-loader` and `imports-loader`
  3. Add the following to the modules section in your webpack.config

```
  module: {
    loaders: [
      {
        test: require.resolve("react"),
        loader: "expose?React"
      },
      {
        test: /\.js$/,
        loader: 'babel-loader?stage=0&optional=runtime',
        exclude: /(node_modules|reactable)/
      },
      {
        test: /reactable.js$/,
        loader: "imports?exports=>undefined"
      }
    ],
    noParse: [
      /reactable.js$/
    ]
  },
```

Works with the latest version but you get lots of `React component classes must extend React.Component.` warnings.

**Comment by glittershark** [comment]
@growlsworth et al, please feel free to comment/reopen if #179 didn't fix this for you. A PR to add tests for webpack inclusion would also be wonderful, as I don't (and haven't ever) use webpack
